import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Soft Stock",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className="overflow-y-scroll scrollbar-w-2 scrollbar
    scrollbar-thumb-primary scroll-smooth"
    >
      <body className={`${inter.className} font-serif`}>{children}</body>
    </html>
  );
}
